### ISSUE TITLE
Acknowledgement of assignment submission (Nice-to-have feature)

### ISSUE THREAD

**Issue by pk1923** [GadgetGlitch/GroupProject-1#11]
The tool should be able to indicate when you submitted the assignment on Canvas and mark it complete with a little cheer sound/animation of completion.

**Comment by GadgetGlitch** [comment]
This feature may be a duplicate as the text already turns read and moves itself to the bottom of the list when marked as Y complete.

**Comment by GadgetGlitch** [comment]
Oh, this issue is for the tracker to have canvas notify it when an assignment has been submitted automatically marking the task as complete. The team realizes that this is beyond our programming and Canvas access capabilities. Although very "Nice to have" for any assignment tracker!

**Comment by GadgetGlitch** [comment]
Will close as not planned.
