### ISSUE TITLE
Highlight assignments for the day in YELLOW (Nice-to-have feature)

### ISSUE THREAD

**Issue by pk1923** [GadgetGlitch/GroupProject-1#12]
The tool should highlight the assignments to work on that day to stay on target. In the color YELLO while also perhaps BOLDing the Black text for emphasis.

**Comment by GadgetGlitch** [comment]
Changed the wording of the title from 'list of" to "Highlight" to clarify the intention of the issue.

**Comment by GadgetGlitch** [comment]
Edited the features main abilities for indicating the tasks are due that specific day.

**Comment by GadgetGlitch** [comment]
Pradeesh finished the code for this issue. It will now be closed.
